_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 75
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 75
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.18.5
            "6": 4.44.1
            "8":
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
batch_size:
    value: 64
epoch:
    value: 20
learning_rate:
    value: 0.005
model:
    value:
        - CLIP
        - all-MiniLM-L6-v2
