_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 33
                - 41
                - 55
            "2":
                - 1
                - 33
                - 41
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
                - 62
            "4": 3.11.5
            "5": 0.18.0
            "8":
                - 3
                - 5
            "12": 0.18.0
            "13": windows-amd64
batch_size:
    value: 32
beta1:
    value: 0.9
beta2:
    value: 0.99
epoch:
    value: 10
epsilon:
    value: 1e-08
learning_rate:
    value: 0.001
model:
    value: ResNet-18
old_batch_size:
    value: null
scaled_train:
    value: false
scheduler:
    value: false
total_training_steps:
    value: 1840
