wandb_version: 1

epoch:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.005
batch_size:
  desc: null
  value: 64
model:
  desc: null
  value:
  - CLIP
  - all-MiniLM-L6-v2
_wandb:
  desc: null
  value:
    python_version: 3.9.20
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729442801.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.20
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
